FROM nginx:stable-alpine
RUN rm -rf /etc/nginx/conf.d
COPY conf /etc/nginx
COPY build /usr/share/nginx/html
RUN apk add --no-cache bash
COPY env.sh /usr/share/nginx/html/env.sh
COPY .env /usr/share/nginx/html/.env
RUN chmod +x /usr/share/nginx/html/env.sh
EXPOSE 80
CMD ["/bin/bash", "-c", "/usr/share/nginx/html/env.sh && nginx -g 'daemon off;'"]
